/* tslint:disable */
/* eslint-disable */
/**
 * Instagram Light API
 * Lightweight Instagram-like API with Go Fiber
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ModelsAuthRequest,
  ModelsErrorResponse,
  ModelsLoginResponse,
  ModelsRegisterResponse,
} from '../models/index';
import {
    ModelsAuthRequestFromJSON,
    ModelsAuthRequestToJSON,
    ModelsErrorResponseFromJSON,
    ModelsErrorResponseToJSON,
    ModelsLoginResponseFromJSON,
    ModelsLoginResponseToJSON,
    ModelsRegisterResponseFromJSON,
    ModelsRegisterResponseToJSON,
} from '../models/index';

export interface ApiAuthLoginPostRequest {
    body: ModelsAuthRequest;
}

export interface ApiAuthRegisterPostRequest {
    body: ModelsAuthRequest;
}

/**
 * 
 */
export class AuthApi extends runtime.BaseAPI {

    /**
     * Login with username and password to get a JWT token
     * Login
     */
    async apiAuthLoginPostRaw(requestParameters: ApiAuthLoginPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ModelsLoginResponse>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling apiAuthLoginPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/auth/login`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ModelsAuthRequestToJSON(requestParameters['body']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ModelsLoginResponseFromJSON(jsonValue));
    }

    /**
     * Login with username and password to get a JWT token
     * Login
     */
    async apiAuthLoginPost(requestParameters: ApiAuthLoginPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ModelsLoginResponse> {
        const response = await this.apiAuthLoginPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Register a new user with username and password
     * Register a new user
     */
    async apiAuthRegisterPostRaw(requestParameters: ApiAuthRegisterPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ModelsRegisterResponse>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling apiAuthRegisterPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/auth/register`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ModelsAuthRequestToJSON(requestParameters['body']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ModelsRegisterResponseFromJSON(jsonValue));
    }

    /**
     * Register a new user with username and password
     * Register a new user
     */
    async apiAuthRegisterPost(requestParameters: ApiAuthRegisterPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ModelsRegisterResponse> {
        const response = await this.apiAuthRegisterPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
