/* tslint:disable */
/* eslint-disable */
/**
 * Instagram Light API
 * Lightweight Instagram-like API with Go Fiber
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ModelsComment,
  ModelsErrorResponse,
} from '../models/index';
import {
    ModelsCommentFromJSON,
    ModelsCommentToJSON,
    ModelsErrorResponseFromJSON,
    ModelsErrorResponseToJSON,
} from '../models/index';

export interface ApiPostsPostIdCommentsCommentIdDeleteRequest {
    postId: number;
    commentId: number;
}

export interface ApiPostsPostIdCommentsGetRequest {
    postId: number;
}

export interface ApiPostsPostIdCommentsPostRequest {
    postId: number;
    body: object;
}

/**
 * 
 */
export class CommentsApi extends runtime.BaseAPI {

    /**
     * Delete a comment by its ID (only by the comment owner)
     * Delete a comment
     */
    async apiPostsPostIdCommentsCommentIdDeleteRaw(requestParameters: ApiPostsPostIdCommentsCommentIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['postId'] == null) {
            throw new runtime.RequiredError(
                'postId',
                'Required parameter "postId" was null or undefined when calling apiPostsPostIdCommentsCommentIdDelete().'
            );
        }

        if (requestParameters['commentId'] == null) {
            throw new runtime.RequiredError(
                'commentId',
                'Required parameter "commentId" was null or undefined when calling apiPostsPostIdCommentsCommentIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/api/posts/{post_id}/comments/{comment_id}`;
        urlPath = urlPath.replace(`{${"post_id"}}`, encodeURIComponent(String(requestParameters['postId'])));
        urlPath = urlPath.replace(`{${"comment_id"}}`, encodeURIComponent(String(requestParameters['commentId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a comment by its ID (only by the comment owner)
     * Delete a comment
     */
    async apiPostsPostIdCommentsCommentIdDelete(requestParameters: ApiPostsPostIdCommentsCommentIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiPostsPostIdCommentsCommentIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Get all comments for a specific post
     * Get comments for a post
     */
    async apiPostsPostIdCommentsGetRaw(requestParameters: ApiPostsPostIdCommentsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ModelsComment>>> {
        if (requestParameters['postId'] == null) {
            throw new runtime.RequiredError(
                'postId',
                'Required parameter "postId" was null or undefined when calling apiPostsPostIdCommentsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/api/posts/{post_id}/comments`;
        urlPath = urlPath.replace(`{${"post_id"}}`, encodeURIComponent(String(requestParameters['postId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ModelsCommentFromJSON));
    }

    /**
     * Get all comments for a specific post
     * Get comments for a post
     */
    async apiPostsPostIdCommentsGet(requestParameters: ApiPostsPostIdCommentsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ModelsComment>> {
        const response = await this.apiPostsPostIdCommentsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a new comment for a specific post
     * Create a comment for a post
     */
    async apiPostsPostIdCommentsPostRaw(requestParameters: ApiPostsPostIdCommentsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ModelsComment>> {
        if (requestParameters['postId'] == null) {
            throw new runtime.RequiredError(
                'postId',
                'Required parameter "postId" was null or undefined when calling apiPostsPostIdCommentsPost().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling apiPostsPostIdCommentsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/api/posts/{post_id}/comments`;
        urlPath = urlPath.replace(`{${"post_id"}}`, encodeURIComponent(String(requestParameters['postId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ModelsCommentFromJSON(jsonValue));
    }

    /**
     * Create a new comment for a specific post
     * Create a comment for a post
     */
    async apiPostsPostIdCommentsPost(requestParameters: ApiPostsPostIdCommentsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ModelsComment> {
        const response = await this.apiPostsPostIdCommentsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
