/* tslint:disable */
/* eslint-disable */
/**
 * Instagram Light API
 * Lightweight Instagram-like API with Go Fiber
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ModelsErrorResponse,
  ModelsFeedResponse,
} from '../models/index';
import {
    ModelsErrorResponseFromJSON,
    ModelsErrorResponseToJSON,
    ModelsFeedResponseFromJSON,
    ModelsFeedResponseToJSON,
} from '../models/index';

export interface ApiFeedGetRequest {
    userId: number;
    page?: number;
    limit?: number;
}

/**
 * 
 */
export class FeedApi extends runtime.BaseAPI {

    /**
     * Get a paginated feed for a user (posts from followed users)
     * Get user feed
     */
    async apiFeedGetRaw(requestParameters: ApiFeedGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ModelsFeedResponse>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling apiFeedGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['userId'] != null) {
            queryParameters['user_id'] = requestParameters['userId'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/api/feed`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ModelsFeedResponseFromJSON(jsonValue));
    }

    /**
     * Get a paginated feed for a user (posts from followed users)
     * Get user feed
     */
    async apiFeedGet(requestParameters: ApiFeedGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ModelsFeedResponse> {
        const response = await this.apiFeedGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
