/* tslint:disable */
/* eslint-disable */
/**
 * Instagram Light API
 * Lightweight Instagram-like API with Go Fiber
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ModelsErrorResponse,
  ModelsUploadResponse,
} from '../models/index';
import {
    ModelsErrorResponseFromJSON,
    ModelsErrorResponseToJSON,
    ModelsUploadResponseFromJSON,
    ModelsUploadResponseToJSON,
} from '../models/index';

export interface ApiUploadPostRequest {
    file: Blob;
}

/**
 * 
 */
export class UploadApi extends runtime.BaseAPI {

    /**
     * Uploads a media file and returns its storage path
     * Upload media file
     */
    async apiUploadPostRaw(requestParameters: ApiUploadPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ModelsUploadResponse>> {
        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling apiUploadPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }


        let urlPath = `/api/upload`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ModelsUploadResponseFromJSON(jsonValue));
    }

    /**
     * Uploads a media file and returns its storage path
     * Upload media file
     */
    async apiUploadPost(requestParameters: ApiUploadPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ModelsUploadResponse> {
        const response = await this.apiUploadPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
