/* tslint:disable */
/* eslint-disable */
/**
 * Instagram Light API
 * Lightweight Instagram-like API with Go Fiber
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelsComment
 */
export interface ModelsComment {
    /**
     * 
     * @type {string}
     * @memberof ModelsComment
     */
    createdAt?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsComment
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsComment
     */
    postId?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsComment
     */
    text?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsComment
     */
    userId?: number;
}

/**
 * Check if a given object implements the ModelsComment interface.
 */
export function instanceOfModelsComment(value: object): value is ModelsComment {
    return true;
}

export function ModelsCommentFromJSON(json: any): ModelsComment {
    return ModelsCommentFromJSONTyped(json, false);
}

export function ModelsCommentFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelsComment {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'id': json['id'] == null ? undefined : json['id'],
        'postId': json['post_id'] == null ? undefined : json['post_id'],
        'text': json['text'] == null ? undefined : json['text'],
        'userId': json['user_id'] == null ? undefined : json['user_id'],
    };
}

export function ModelsCommentToJSON(json: any): ModelsComment {
    return ModelsCommentToJSONTyped(json, false);
}

export function ModelsCommentToJSONTyped(value?: ModelsComment | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': value['createdAt'],
        'id': value['id'],
        'post_id': value['postId'],
        'text': value['text'],
        'user_id': value['userId'],
    };
}

