/* tslint:disable */
/* eslint-disable */
/**
 * Instagram Light API
 * Lightweight Instagram-like API with Go Fiber
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelsToggleLikeResponse
 */
export interface ModelsToggleLikeResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ModelsToggleLikeResponse
     */
    liked?: boolean;
}

/**
 * Check if a given object implements the ModelsToggleLikeResponse interface.
 */
export function instanceOfModelsToggleLikeResponse(value: object): value is ModelsToggleLikeResponse {
    return true;
}

export function ModelsToggleLikeResponseFromJSON(json: any): ModelsToggleLikeResponse {
    return ModelsToggleLikeResponseFromJSONTyped(json, false);
}

export function ModelsToggleLikeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelsToggleLikeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'liked': json['liked'] == null ? undefined : json['liked'],
    };
}

export function ModelsToggleLikeResponseToJSON(json: any): ModelsToggleLikeResponse {
    return ModelsToggleLikeResponseToJSONTyped(json, false);
}

export function ModelsToggleLikeResponseToJSONTyped(value?: ModelsToggleLikeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'liked': value['liked'],
    };
}

