/* tslint:disable */
/* eslint-disable */
/**
 * Instagram Light API
 * Lightweight Instagram-like API with Go Fiber
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelsPostWithLikes
 */
export interface ModelsPostWithLikes {
    /**
     * 
     * @type {string}
     * @memberof ModelsPostWithLikes
     */
    caption?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsPostWithLikes
     */
    createdAt?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ModelsPostWithLikes
     */
    flagged?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ModelsPostWithLikes
     */
    id?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ModelsPostWithLikes
     */
    isLiked?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ModelsPostWithLikes
     */
    likesCount?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsPostWithLikes
     */
    mediaUrl?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsPostWithLikes
     */
    userId?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsPostWithLikes
     */
    username?: string;
}

/**
 * Check if a given object implements the ModelsPostWithLikes interface.
 */
export function instanceOfModelsPostWithLikes(value: object): value is ModelsPostWithLikes {
    return true;
}

export function ModelsPostWithLikesFromJSON(json: any): ModelsPostWithLikes {
    return ModelsPostWithLikesFromJSONTyped(json, false);
}

export function ModelsPostWithLikesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelsPostWithLikes {
    if (json == null) {
        return json;
    }
    return {
        
        'caption': json['caption'] == null ? undefined : json['caption'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'flagged': json['flagged'] == null ? undefined : json['flagged'],
        'id': json['id'] == null ? undefined : json['id'],
        'isLiked': json['is_liked'] == null ? undefined : json['is_liked'],
        'likesCount': json['likes_count'] == null ? undefined : json['likes_count'],
        'mediaUrl': json['media_url'] == null ? undefined : json['media_url'],
        'userId': json['user_id'] == null ? undefined : json['user_id'],
        'username': json['username'] == null ? undefined : json['username'],
    };
}

export function ModelsPostWithLikesToJSON(json: any): ModelsPostWithLikes {
    return ModelsPostWithLikesToJSONTyped(json, false);
}

export function ModelsPostWithLikesToJSONTyped(value?: ModelsPostWithLikes | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'caption': value['caption'],
        'created_at': value['createdAt'],
        'flagged': value['flagged'],
        'id': value['id'],
        'is_liked': value['isLiked'],
        'likes_count': value['likesCount'],
        'media_url': value['mediaUrl'],
        'user_id': value['userId'],
        'username': value['username'],
    };
}

