/* tslint:disable */
/* eslint-disable */
/**
 * Instagram Light API
 * Lightweight Instagram-like API with Go Fiber
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelsLoginResponse
 */
export interface ModelsLoginResponse {
    /**
     * 
     * @type {string}
     * @memberof ModelsLoginResponse
     */
    token?: string;
}

/**
 * Check if a given object implements the ModelsLoginResponse interface.
 */
export function instanceOfModelsLoginResponse(value: object): value is ModelsLoginResponse {
    return true;
}

export function ModelsLoginResponseFromJSON(json: any): ModelsLoginResponse {
    return ModelsLoginResponseFromJSONTyped(json, false);
}

export function ModelsLoginResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelsLoginResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'] == null ? undefined : json['token'],
    };
}

export function ModelsLoginResponseToJSON(json: any): ModelsLoginResponse {
    return ModelsLoginResponseToJSONTyped(json, false);
}

export function ModelsLoginResponseToJSONTyped(value?: ModelsLoginResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
    };
}

