/* tslint:disable */
/* eslint-disable */
/**
 * Instagram Light API
 * Lightweight Instagram-like API with Go Fiber
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelsAuthRequest
 */
export interface ModelsAuthRequest {
    /**
     * 
     * @type {string}
     * @memberof ModelsAuthRequest
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsAuthRequest
     */
    password?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsAuthRequest
     */
    username?: string;
}

/**
 * Check if a given object implements the ModelsAuthRequest interface.
 */
export function instanceOfModelsAuthRequest(value: object): value is ModelsAuthRequest {
    return true;
}

export function ModelsAuthRequestFromJSON(json: any): ModelsAuthRequest {
    return ModelsAuthRequestFromJSONTyped(json, false);
}

export function ModelsAuthRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelsAuthRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
        'password': json['password'] == null ? undefined : json['password'],
        'username': json['username'] == null ? undefined : json['username'],
    };
}

export function ModelsAuthRequestToJSON(json: any): ModelsAuthRequest {
    return ModelsAuthRequestToJSONTyped(json, false);
}

export function ModelsAuthRequestToJSONTyped(value?: ModelsAuthRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
        'username': value['username'],
    };
}

