/* tslint:disable */
/* eslint-disable */
/**
 * Instagram Light API
 * Lightweight Instagram-like API with Go Fiber
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelsUploadResponse
 */
export interface ModelsUploadResponse {
    /**
     * 
     * @type {string}
     * @memberof ModelsUploadResponse
     */
    mediaUrl?: string;
}

/**
 * Check if a given object implements the ModelsUploadResponse interface.
 */
export function instanceOfModelsUploadResponse(value: object): value is ModelsUploadResponse {
    return true;
}

export function ModelsUploadResponseFromJSON(json: any): ModelsUploadResponse {
    return ModelsUploadResponseFromJSONTyped(json, false);
}

export function ModelsUploadResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelsUploadResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'mediaUrl': json['media_url'] == null ? undefined : json['media_url'],
    };
}

export function ModelsUploadResponseToJSON(json: any): ModelsUploadResponse {
    return ModelsUploadResponseToJSONTyped(json, false);
}

export function ModelsUploadResponseToJSONTyped(value?: ModelsUploadResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'media_url': value['mediaUrl'],
    };
}

