/* tslint:disable */
/* eslint-disable */
/**
 * Instagram Light API
 * Lightweight Instagram-like API with Go Fiber
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelsPost
 */
export interface ModelsPost {
    /**
     * 
     * @type {string}
     * @memberof ModelsPost
     */
    caption?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsPost
     */
    createdAt?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ModelsPost
     */
    flagged?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ModelsPost
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsPost
     */
    mediaUrl?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsPost
     */
    userId?: number;
}

/**
 * Check if a given object implements the ModelsPost interface.
 */
export function instanceOfModelsPost(value: object): value is ModelsPost {
    return true;
}

export function ModelsPostFromJSON(json: any): ModelsPost {
    return ModelsPostFromJSONTyped(json, false);
}

export function ModelsPostFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelsPost {
    if (json == null) {
        return json;
    }
    return {
        
        'caption': json['caption'] == null ? undefined : json['caption'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'flagged': json['flagged'] == null ? undefined : json['flagged'],
        'id': json['id'] == null ? undefined : json['id'],
        'mediaUrl': json['media_url'] == null ? undefined : json['media_url'],
        'userId': json['user_id'] == null ? undefined : json['user_id'],
    };
}

export function ModelsPostToJSON(json: any): ModelsPost {
    return ModelsPostToJSONTyped(json, false);
}

export function ModelsPostToJSONTyped(value?: ModelsPost | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'caption': value['caption'],
        'created_at': value['createdAt'],
        'flagged': value['flagged'],
        'id': value['id'],
        'media_url': value['mediaUrl'],
        'user_id': value['userId'],
    };
}

