/* tslint:disable */
/* eslint-disable */
/**
 * Instagram Light API
 * Lightweight Instagram-like API with Go Fiber
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelsRegisterResponse
 */
export interface ModelsRegisterResponse {
    /**
     * 
     * @type {string}
     * @memberof ModelsRegisterResponse
     */
    message?: string;
}

/**
 * Check if a given object implements the ModelsRegisterResponse interface.
 */
export function instanceOfModelsRegisterResponse(value: object): value is ModelsRegisterResponse {
    return true;
}

export function ModelsRegisterResponseFromJSON(json: any): ModelsRegisterResponse {
    return ModelsRegisterResponseFromJSONTyped(json, false);
}

export function ModelsRegisterResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelsRegisterResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function ModelsRegisterResponseToJSON(json: any): ModelsRegisterResponse {
    return ModelsRegisterResponseToJSONTyped(json, false);
}

export function ModelsRegisterResponseToJSONTyped(value?: ModelsRegisterResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

