/* tslint:disable */
/* eslint-disable */
/**
 * Instagram Light API
 * Lightweight Instagram-like API with Go Fiber
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelsPostWithLikes } from './ModelsPostWithLikes';
import {
    ModelsPostWithLikesFromJSON,
    ModelsPostWithLikesFromJSONTyped,
    ModelsPostWithLikesToJSON,
    ModelsPostWithLikesToJSONTyped,
} from './ModelsPostWithLikes';

/**
 * 
 * @export
 * @interface ModelsFeedResponse
 */
export interface ModelsFeedResponse {
    /**
     * 
     * @type {number}
     * @memberof ModelsFeedResponse
     */
    limit?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsFeedResponse
     */
    page?: number;
    /**
     * 
     * @type {Array<ModelsPostWithLikes>}
     * @memberof ModelsFeedResponse
     */
    posts?: Array<ModelsPostWithLikes>;
}

/**
 * Check if a given object implements the ModelsFeedResponse interface.
 */
export function instanceOfModelsFeedResponse(value: object): value is ModelsFeedResponse {
    return true;
}

export function ModelsFeedResponseFromJSON(json: any): ModelsFeedResponse {
    return ModelsFeedResponseFromJSONTyped(json, false);
}

export function ModelsFeedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelsFeedResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'limit': json['limit'] == null ? undefined : json['limit'],
        'page': json['page'] == null ? undefined : json['page'],
        'posts': json['posts'] == null ? undefined : ((json['posts'] as Array<any>).map(ModelsPostWithLikesFromJSON)),
    };
}

export function ModelsFeedResponseToJSON(json: any): ModelsFeedResponse {
    return ModelsFeedResponseToJSONTyped(json, false);
}

export function ModelsFeedResponseToJSONTyped(value?: ModelsFeedResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'limit': value['limit'],
        'page': value['page'],
        'posts': value['posts'] == null ? undefined : ((value['posts'] as Array<any>).map(ModelsPostWithLikesToJSON)),
    };
}

