/* tslint:disable */
/* eslint-disable */
/**
 * Instagram Light API
 * Lightweight Instagram-like API with Go Fiber
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelsPost } from './ModelsPost';
import {
    ModelsPostFromJSON,
    ModelsPostFromJSONTyped,
    ModelsPostToJSON,
    ModelsPostToJSONTyped,
} from './ModelsPost';

/**
 * 
 * @export
 * @interface ModelsPostsResponse
 */
export interface ModelsPostsResponse {
    /**
     * 
     * @type {number}
     * @memberof ModelsPostsResponse
     */
    limit?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsPostsResponse
     */
    page?: number;
    /**
     * 
     * @type {Array<ModelsPost>}
     * @memberof ModelsPostsResponse
     */
    posts?: Array<ModelsPost>;
}

/**
 * Check if a given object implements the ModelsPostsResponse interface.
 */
export function instanceOfModelsPostsResponse(value: object): value is ModelsPostsResponse {
    return true;
}

export function ModelsPostsResponseFromJSON(json: any): ModelsPostsResponse {
    return ModelsPostsResponseFromJSONTyped(json, false);
}

export function ModelsPostsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelsPostsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'limit': json['limit'] == null ? undefined : json['limit'],
        'page': json['page'] == null ? undefined : json['page'],
        'posts': json['posts'] == null ? undefined : ((json['posts'] as Array<any>).map(ModelsPostFromJSON)),
    };
}

export function ModelsPostsResponseToJSON(json: any): ModelsPostsResponse {
    return ModelsPostsResponseToJSONTyped(json, false);
}

export function ModelsPostsResponseToJSONTyped(value?: ModelsPostsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'limit': value['limit'],
        'page': value['page'],
        'posts': value['posts'] == null ? undefined : ((value['posts'] as Array<any>).map(ModelsPostToJSON)),
    };
}

